trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'website'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    appName: 'devops-demo'
    package: '$(Build.ArtifactStagingDirectory)'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'devops-demo'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|22-lts'
    DeploymentTypeLinux: 'oneDeploy'